export const DIALOG_BOTTOM_PADDING = 115;
export const DIALOG_TOP_STRIP_HEIGHT = 215;
export const DIALOG_BOTTOM_VISIBLE_STRIP_HEIGHT = 215;
export const DIALOG_BOTTOM_STRIP_HEIGHT = 215 + DIALOG_BOTTOM_PADDING;
