
enum CellType {
    EMPTY, FOREST, MOUNTAIN, SAND, BERRY_FIELD, WATER, IVY_SMALL, IVY, IVY_STRONG, PLANK1, PLANK2, PLANK3,
    IVY_SMALL_M, IVY_M, IVY_STRONG_M, PLANK1_M, PLANK2_M, PLANK3_M, COMPASS_IVY, COMPASS_FREE, CANKERBERRY1, CANKERBERRY2, COLD,
    ACORN, VISION, VISION_IVY, ROCKET, ROCKET_IVY, ROCKET2, ROCKET_IVY2, ROCKET3, ROCKET_IVY3, DRAGONFLY, HIVE, BOAT, JELLY, 
}
//TODO: EditorCellType и CellType. Побочную информацию сразу сохранять в ForestCell. 


export default CellType;
